services:
  uploader:
    image: javierrodriguez4/uploader:1.0.0
    container_name: uploader
    ports:
      - "8082:8080"
      - "2022:2022"
      - "2121:2121"
      - "10080:10080"
    volumes:
      - ./uploaderdata:/srv/sftpgo
      - ./uploaderhome:/var/lib/sftpgo
    environment:
      - SFTPGO_HTTPD_BINDINGS_0_PORT=8080
      - SFTPGO_HTTPD_BINDINGS_0_ADDRESS=0.0.0.0
      - SFTPGO_DATA_PROVIDER_CREATE_DEFAULT_ADMIN=true
      - SFTPGO_WEBDAVD_BINDINGS_0_PORT=10080
      - SFTPGO_FTPD_BINDINGS_0_PORT=2121
      - SFTPGO_FTPD_BINDINGS_0_FORCE_PASSIVE_IP='127.0.0.1:8080'
    restart: unless-stopped
    user: "0:0"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  nginx:
    image: nginx:latest
    container_name: nginx_uploader
    ports:
      - "8085:8085"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - uploader
    restart: unless-stopped

volumes:
  uploaderdata:
    driver_opts:
      type: none
      o: bind
      device: ./uploaderdata
  uploaderhome:
    driver_opts:
      type: none
      o: bind
      device: ./uploaderhome
